version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8081:8081"
    command: ["fastapi", "run", "main.py", "--port", "8081"]
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8081/get/" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3

