# Generated by Django 5.1.1 on 2024-09-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('file_upload', models.FileField(upload_to='')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
